# Generated by Django 3.0.2 on 2020-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='mpin',
            field=models.IntegerField(default=1111),
            preserve_default=False,
        ),
    ]
