# Generated by Django 3.0.2 on 2020-01-23 09:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_farmer_mpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('aadhar_no', models.BigIntegerField()),
                ('mpin', models.IntegerField()),
                ('occupation', models.CharField(max_length=25)),
                ('field_of_interest', models.CharField(max_length=25)),
            ],
        ),
    ]
