# Generated by Django 3.0.2 on 2020-01-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_agriexpert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriexpert',
            name='field_of_interest',
        ),
        migrations.RemoveField(
            model_name='agriexpert',
            name='occupation',
        ),
    ]
