# Generated by Django 3.0.2 on 2020-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_agriexpert_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriexpert',
            name='field_of_interest',
            field=models.CharField(default='crop', max_length=25),
            preserve_default=False,
        ),
    ]
