# Generated by Django 3.0.2 on 2020-01-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_agriassistance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgriAssistance',
            new_name='AgriAssistant',
        ),
    ]
