# Generated by Django 3.0.2 on 2020-02-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_cities_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
    ]
