# Generated by Django 3.0.2 on 2020-02-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_remove_cities_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takukas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka_name', models.CharField(max_length=30)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Cities')),
            ],
        ),
    ]
