# Generated by Django 3.0.2 on 2020-02-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_takukas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Takukas',
            new_name='Talukas',
        ),
    ]
