# Generated by Django 3.0.2 on 2020-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20200203_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriassistant',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='agriexpert',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
